print("--------------------------------")
print("Assignment 01")
print("--------------------------------")
nim= str(input("NIM      : "))
nama= str(input("Nama     : "))
angkatan= int(input("Angkatan : "))
prodi= str(input("Prodi    : "))

print("--------------------------------")
print("Hasil")
print("--------------------------------")
print("NIM      :", nim)
print("Nama     :", nama)
print("Angkatan :", angkatan)
print("Prodi    :", prodi)
print("--------------------------------")
print("Fakultas Ilmu Komputer")
print("Universitas 'Amikom' Yogyakarta")
