print("--------------------------------")
print("Assignment 01")
print("--------------------------------")
print("NIM      : 18.01.4119")
print("Nama     : Veto Wardana Putra")
print("Angkatan : 2018")
print("Prodi    : D3 Teknik Informatika")
print("--------------------------------")
print("Fakultas Ilmu Komputer")
print("Universitas 'Amikom' Yogyakarta")
